__version__ = "0.0.1"

from erpnext.controllers.taxes_and_totals import calculate_taxes_and_totals
from nextfood.overrides.taxes_and_totals import custom_calculate_taxes_and_totals


calculate_taxes_and_totals.calculate_item_values = custom_calculate_taxes_and_totals.custom_calculate_item_values
